name: Chowbus Phobos
on: [ pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Testing Kafka
        run: docker-compose up -d --force-recreate kafka zookeeper
      - name: Build docker image
        run: docker-compose build test
      - name: wait for kafka
        run: sleep 6
      - name: Run Tests
        run: docker-compose run --rm test
