name: Ruby Gem Publish

on:
  push:
    branches:
      - master
    tags:
      - v3.**

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.3 # to match monolith
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build phobos.gemspec
        gem push *.gem
      env:
        #GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        GEM_HOST_API_KEY: "reachlin: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"
